export const animalList = [
  'Albatross',
  'Alpaca',
  'Ant',
  'Bat',
  'Bear',
  'Bird',
  'Black',
  'Blackbuck',
  'Brown',
  'Buffalo',
  'Bulbul',
  'Butterfly',
  'Cat',
  'Cheetah',
  'Chinkara',
  'Cobra',
  'Cockroach',
  'Cow',
  'Crocodile',
  'Deer',
  'Dog',
  'Dolphin',
  'Eagle',
  'Earthworm',
  'Elephant',
  'Fish',
  'Gaur',
  'Gavial',
  'Giraffe',
  'Goat',
  'Grasshopper',
  'Hen',
  'Hippopotamus',
  'Honey Badger',
  'Horse',
  'Housefly',
  'Koel',
  'Leopard',
  'Lion',
  'Lizard',
  'Monkey',
  'Mosquito',
  'Nilgai',
  'Parrot',
  'Peacock',
  'Pigeon',
  'Polar',
  'Prawn',
  'Rabbit',
  'Rat',
  'Rat',
  'Rattle',
  'Rhesus',
  'Rhinoceros',
  'Sea',
  'Shrimp',
  'Sheep',
  'Snake',
  'Snakehead',
  'Sparrow',
  'Spider',
  'Starfish',
  'Tiger',
  'Tiger',
  'Walrus',
  'Wasp',
  'Weasel',
  'Whale',
  'Wolf',
  'Zebra',
];

export const descriptors = [
  'affectionate',
  'agreeable',
  'amiable',
  'bright',
  'charming',
  'creative',
  'determined',
  'diligent',
  'diplomatic',
  'dynamic',
  'energetic',
  'friendly',
  'funny',
  'generous',
  'giving',
  'gregarious',
  'hardworking',
  'helpful',
  'kind',
  'likable',
  'loyal',
  'patient',
  'polite',
  'sincere',
  'amazing',
  'awesome',
  'blithesome',
  'excellent',
  'fabulous',
  'favorable',
  'fortuitous',
  'gorgeous',
  'incredible',
  'unique',
  'mirthful',
  'outstanding',
  'perfect',
  'philosophical',
  'propitious',
  'remarkable',
  'rousing',
  'spectacular',
  'splendid',
  'stellar',
  'stupendous',
  'super',
  'upbeat',
  'stunning',
  'wondrous',
];

/**
 * generates and returns a list of random animal names
 * @param {number} count of animal names
 * @returns {string[]}
 */
export function getRandomAnimalNames(count){
  let NamesOut = [];
  const animalListCopy = [...animalList];
  const descriptorListCopy = [...descriptors];
  for (let i = 0; i< count;i++ ){
    const descriptIndex = Math.floor(Math.random() * descriptorListCopy.length) ;
    const animalIndex = Math.floor(Math.random() * animalListCopy.length);

    NamesOut.push(`${descriptorListCopy[descriptIndex][0].toUpperCase() + descriptorListCopy[descriptIndex].substr(1)} ${animalListCopy[animalIndex]}`);
    animalListCopy.splice(animalIndex,1);
    descriptorListCopy.splice(descriptIndex,1);
  }

  return NamesOut;
}
